# Generated by Django 5.1.12 on 2026-02-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_partner_partnermembership_delete_portaluser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMentorshipAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_availabilities', to='portal.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMentorshipFormMentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_form_mentees', to='portal.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMentorshipFormMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_form_mentors', to='portal.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMentorshipPublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_public_keys', to='portal.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMentorshipFormMentorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portal.partnermentorshipformmentor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_form_mentor_responses', to='portal.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_responses', to=settings.AUTH_USER_MODEL)),
                ('public_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_responses', to='portal.partnermentorshippublickey')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMentorshipFormMenteeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portal.partnermentorshipformmentee')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_form_mentee_responses', to='portal.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_responses', to=settings.AUTH_USER_MODEL)),
                ('public_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_responses', to='portal.partnermentorshippublickey')),
            ],
        ),
    ]
