# Generated by Django 5.1.12 on 2026-02-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_remove_organization_display_name_organizationname'),
        ('portal', '0003_partnermentorshipavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='orgs.organization'),
        ),
    ]
