# Generated by Django 5.1.12 on 2026-02-20 19:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_form_public_keys(apps, schema_editor): # pragma: no cover
    MentorResponse = apps.get_model('portal', 'PartnerMentorshipFormMentorResponse')
    MenteeResponse = apps.get_model('portal', 'PartnerMentorshipFormMenteeResponse')
    MentorForm = apps.get_model('portal', 'PartnerMentorshipFormMentor')
    MenteeForm = apps.get_model('portal', 'PartnerMentorshipFormMentee')

    for response in MentorResponse.objects.exclude(public_key_id=None).iterator():
        MentorForm.objects.filter(id=response.form_id, public_key_id__isnull=True).update(public_key_id=response.public_key_id)

    for response in MenteeResponse.objects.exclude(public_key_id=None).iterator():
        MenteeForm.objects.filter(id=response.form_id, public_key_id__isnull=True).update(public_key_id=response.public_key_id)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_partner_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermentorshipformmentee',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_forms', to='portal.partnermentorshippublickey'),
        ),
        migrations.AddField(
            model_name='partnermentorshipformmentor',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_forms', to='portal.partnermentorshippublickey'),
        ),
        migrations.RunPython(backfill_form_public_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='partnermentorshipformmenteeresponse',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='partnermentorshipformmentorresponse',
            name='public_key',
        ),
    ]
