# Generated by Django 5.1.12 on 2026-03-02 18:11

import django.db.models.deletion
from django.db import migrations, models
from django.core.exceptions import ValidationError

def migrate_availability_to_mentorship(apps, schema_editor):
    partner_model = apps.get_model('portal', 'Partner')
    for partner in partner_model.objects.all():
        partner.mentorship = partner.mentorship_availabilities.filter(status=True).exists()
        partner.save()

def migrate_mentorship_to_availability(apps, schema_editor):
    partner_model = apps.get_model('portal', 'Partner')
    availability_model = apps.get_model('portal', 'PartnerMentorshipAvailability')
    for partner in partner_model.objects.all():
        availability_model.objects.create(partner=partner, status=partner.mentorship)

def migrate_orgs_foreign_key_to_one_to_one(apps, schema_editor):
    # Check if there are any partners without a corresponding organization or with multiple partners for the same organization
    if apps.get_model('portal', 'Partner').objects.filter(organization__isnull=True).exists():
        raise ValidationError("Cannot migrate to one-to-one: Some partners do not have an associated organization.")
    if apps.get_model('portal', 'Partner').objects.values('organization').annotate(count=models.Count('id')).filter(count__gt=1).exists():
        raise ValidationError("Cannot migrate to one-to-one: Some organizations are associated with multiple partners.")
    
    partner_model = apps.get_model('portal', 'Partner')
    for partner in partner_model.objects.all():
        partner.organization_new_id = partner.organization_id
        partner.save()

def migrate_orgs_one_to_one_to_foreign_key(apps, schema_editor):
    partner_model = apps.get_model('portal', 'Partner')
    for partner in partner_model.objects.all():
        partner.organization_id = partner.organization_new_id
        partner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_remove_organization_display_name_organizationname'),
        ('portal', '0005_remove_partnermentorshipformmenteeresponse_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mentorship',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_availability_to_mentorship, reverse_code=migrate_mentorship_to_availability),
        migrations.DeleteModel(
            name='PartnerMentorshipAvailability',
        ),
        migrations.AddField(
            model_name='partner',
            name='organization_new',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='orgs.organization', null=True),
        ),
        migrations.RunPython(migrate_orgs_foreign_key_to_one_to_one, reverse_code=migrate_orgs_one_to_one_to_foreign_key),
        migrations.RemoveField(
            model_name='partner',
            name='organization',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
