# Generated by Django 6.0.3 on 2026-03-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_remove_organization_display_name_organizationname'),
        ('portal', '0006_remove_partner_name_partner_mentorship_and_more'),
        ('skills', '0006_hashtag'),
        ('users', '0035_territory_territory_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='orgs.organization'),
        ),
        migrations.CreateModel(
            name='PartnerMentorshipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(related_name='mentorship_settings', to='users.language')),
                ('mentee_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_settings_as_mentee_form', to='portal.partnermentorshipformmentee')),
                ('mentor_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_settings_as_mentor_form', to='portal.partnermentorshipformmentor')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_settings', to='portal.partner')),
                ('skills', models.ManyToManyField(related_name='mentorship_settings', to='skills.skill')),
            ],
        ),
    ]
