# Generated by Django 6.0.3 on 2026-03-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_remove_organization_display_name_organizationname'),
        ('portal', '0006_remove_partner_name_partner_mentorship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='orgs.organization'),
        ),
    ]
