# Generated by Django 6.0.3 on 2026-03-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_partner_organization_partnermentorshipsettings'),
        ('users', '0035_territory_territory_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermentorshipsettings',
            name='registration_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnermentorshipsettings',
            name='registration_open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnermentorshipsettings',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_settings', to='users.territory'),
        ),
    ]
