# Generated by Django 6.0.3 on 2026-06-02 00:00

import hashlib
from django.db import migrations, models


def _fingerprint(public_key_text, length=12):
    if not public_key_text:
        return ""
    normalized = "".join(str(public_key_text).split())
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:length]


def backfill_response_key_snapshots(apps, schema_editor):
    MentorResponse = apps.get_model('portal', 'PartnerMentorshipFormMentorResponse')
    MenteeResponse = apps.get_model('portal', 'PartnerMentorshipFormMenteeResponse')

    for response in MentorResponse.objects.select_related('form__public_key').all().iterator():
        if not response.form_id:
            continue
        response.encrypted_with_public_key_id_snapshot = response.form.public_key_id
        if response.form.public_key_id and response.form.public_key:
            response.encrypted_with_public_key_fingerprint = _fingerprint(response.form.public_key.public_key)
        response.save(update_fields=['encrypted_with_public_key_id_snapshot', 'encrypted_with_public_key_fingerprint'])

    for response in MenteeResponse.objects.select_related('form__public_key').all().iterator():
        if not response.form_id:
            continue
        response.encrypted_with_public_key_id_snapshot = response.form.public_key_id
        if response.form.public_key_id and response.form.public_key:
            response.encrypted_with_public_key_fingerprint = _fingerprint(response.form.public_key.public_key)
        response.save(update_fields=['encrypted_with_public_key_id_snapshot', 'encrypted_with_public_key_fingerprint'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_partnermentorshipsettings_registration_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermentorshipformmenteeresponse',
            name='encrypted_with_public_key_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='partnermentorshipformmenteeresponse',
            name='encrypted_with_public_key_id_snapshot',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partnermentorshipformmentorresponse',
            name='encrypted_with_public_key_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='partnermentorshipformmentorresponse',
            name='encrypted_with_public_key_id_snapshot',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_response_key_snapshots, noop_reverse),
    ]
