# Generated by Django 5.1.12 on 2025-11-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_error_message_alter_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
