# Generated by Django 4.2.11 on 2024-10-24 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_organization_acronym_and_more'),
        ('skills', '0004_alter_skill_skill_type_and_more'),
        ('users', '0010_language_language_autonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_autonym',
            field=models.CharField(blank=True, help_text='Name of the language in the language itself', max_length=128, verbose_name='Language autonym'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(help_text='Code of the language', max_length=10, unique=True, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(help_text='Name of the language (in English)', max_length=128, verbose_name='Language name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Short bio of the user.', max_length=2000, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.ManyToManyField(blank=True, help_text='ID of the organization that the user is affiliated with.', related_name='user_affiliation', to='orgs.organization', verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name of the user.', max_length=387, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='ID of the language that the user speaks.', related_name='user_language', to='users.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL of the profile image from Commons.', null=True, verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('he-him', 'He/Him'), ('she-her', 'She/Her'), ('they-them', 'They/Them'), ('not-specified', 'Not specified'), ('other', 'Other')], help_text='Pronoun of the user.', max_length=20, verbose_name='Pronoun'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_available',
            field=models.ManyToManyField(blank=True, help_text='List of IDs of skills that the user is available to teach.', related_name='user_available_skills', to='skills.skill', verbose_name='Available capacity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_known',
            field=models.ManyToManyField(blank=True, help_text='List of IDs of skills that the user knows.', related_name='user_known_skils', to='skills.skill', verbose_name='Known capacity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, help_text='List of IDs of skills that the user wants to learn.', related_name='user_desired_skils', to='skills.skill', verbose_name='Wanted capacity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, help_text='Name of the team that the user is part of.', max_length=128, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='territory',
            field=models.ManyToManyField(blank=True, help_text='ID of the territory that the user is based in.', related_name='user_territory', to='users.territory', verbose_name='Territory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wiki_alt',
            field=models.CharField(blank=True, help_text='Wikimedia alternative account of the user.', max_length=128, verbose_name='Wikimedia alternative account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wikidata_qid',
            field=models.CharField(blank=True, help_text='Wikidata Qid of the user.', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Wikidata Qid format. The format should be Q12345', regex='^Q[1-9]\\d*$')], verbose_name='Wikidata Qid'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wikimedia_project',
            field=models.ManyToManyField(blank=True, help_text='ID of the Wikimedia project that the user contributes to.', related_name='user_wikimedia_project', to='users.wikimediaproject', verbose_name='Wikimedia project'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='parent_territory',
            field=models.ManyToManyField(blank=True, help_text='Parent territory of the territory', related_name='territory_parent', to='users.territory', verbose_name='Parent territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='territory_name',
            field=models.CharField(help_text='Name of the territory', max_length=128, unique=True, verbose_name='Territory name'),
        ),
        migrations.AlterField(
            model_name='wikimediaproject',
            name='wikimedia_project_code',
            field=models.CharField(help_text='Code of the Wikimedia project', max_length=40, unique=True, verbose_name='Wikimedia project code'),
        ),
        migrations.AlterField(
            model_name='wikimediaproject',
            name='wikimedia_project_name',
            field=models.CharField(help_text='Name of the Wikimedia project', max_length=128, verbose_name='Wikimedia project name'),
        ),
    ]
