# Generated by Django 4.2.11 on 2024-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_language_language_autonym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Oauth token')),
                ('extra', models.CharField(max_length=255, verbose_name='Extra info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
