# Generated by Django 4.2.11 on 2025-01-09 18:53

from django.db import migrations, models
import django.db.models.deletion

def create_language_proficiency(apps, schema_editor):
    for profile in apps.get_model('users', 'Profile').objects.all():
        for language in profile.language.all():
            apps.get_model('users', 'LanguageProficiency').objects.create(
                profile=profile,
                language=language,
                proficiency=''
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_authextrainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(blank=True, choices=[(0, '0 - No proficiency'), (1, '1 - Basic proficiency'), (2, '2 - Intermediate proficiency'), (3, '3 - Advanced proficiency'), (4, '4 - "Near-native" proficiency'), (5, '5 - Professional proficiency'), ('n', 'n - Native proficiency')], max_length=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'language')},
            },
        ),
        migrations.RunPython(create_language_proficiency),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
