# Generated by Django 4.2.11 on 2025-01-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_languageproficiency_alter_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(help_text='URL of the avatar', verbose_name='Avatar URL')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, help_text='ID of the avatar that the user uses.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.avatar', verbose_name='Avatar'),
        ),
    ]
