# Generated by Django 4.2.11 on 2025-01-11 01:29

from django.db import migrations, models

def fill_wikimedia_project_picture(apps, schema_editor):
    for wikimedia_project in apps.get_model('users', 'WikimediaProject').objects.all():
        match wikimedia_project.wikimedia_project_code:
            case 'wiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/8/80/Wikipedia-logo-v2.svg'
            case 'wiktionarywiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Wiktionary-logo.svg'
            case 'wikibookswiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Wikibooks-logo.svg'
            case 'wikinews':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/2/24/Wikinews-logo.svg'
            case 'wikiquotewiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Wikiquote-logo.svg'
            case 'wikisourcewiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg'
            case 'wikiversitywiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/9/91/Wikiversity-logo.svg'
            case 'wikivoyagewiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Wikivoyage-logo.svg'
            case 'commonswiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Commons-logo.svg'
            case 'wikidatawiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Wikidata-logo.svg'
            case 'wikispecieswiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/d/df/Wikispecies-logo.svg'
            case 'wikifunctionswiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Wikifunctions-logo.svg'
            case 'metawiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/7/75/Wikimedia_Community_Logo.svg'
            case 'mediawiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/a/a6/MediaWiki-2020-icon.svg'
            case 'wikimaniawiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/5/57/Wikimania.svg'
            case 'incubatorwiki':
                logo = 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Incubator-logo.svg'

        wikimedia_project.wikimedia_project_picture = logo
        wikimedia_project.save()

def undo_fill_wikimedia_project_picture(apps, schema_editor):
    apps.get_model('users', 'WikimediaProject').objects.update(wikimedia_project_picture='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_languageproficiency_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikimediaproject',
            name='wikimedia_project_picture',
            field=models.URLField(blank=True, help_text='Picture of the Wikimedia project', max_length=255, verbose_name='Wikimedia project picture'),
        ),
        migrations.RunPython(fill_wikimedia_project_picture, undo_fill_wikimedia_project_picture),
    ]
