# Generated by Django 4.2.11 on 2025-02-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_wikimediaproject_wikimedia_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=None, help_text='ID of the avatar that the user uses.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.avatar', verbose_name='Avatar'),
        ),
    ]
