# Generated by Django 4.2.11 on 2025-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_datahash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahash',
            name='hash_value',
            field=models.TextField(),
        ),
    ]
