# Generated by Django 4.2.11 on 2025-03-24 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_datahash_hash_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('learner', 'Learner'), ('sharer', 'Sharer')], max_length=7)),
                ('entity', models.CharField(choices=[('user', 'User'), ('org', 'Organization')], max_length=4)),
                ('entity_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'relation', 'entity', 'entity_id')},
            },
        ),
    ]
