# Generated by Django 4.2.11 on 2025-03-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_organization_report'),
        ('users', '0019_saveditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='related_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(condition=models.Q(('entity', 'user')), fields=('user', 'relation', 'entity', 'related_user'), name='unique_user_relation_entity_related_user'),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(condition=models.Q(('entity', 'org')), fields=('user', 'relation', 'entity', 'related_org'), name='unique_user_relation_entity_related_org'),
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='entity_id',
        ),
    ]
