# Generated by Django 4.2.11 on 2025-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_saveditem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saveditem',
            name='unique_user_relation_entity_related_user',
        ),
        migrations.RemoveConstraint(
            model_name='saveditem',
            name='unique_user_relation_entity_related_org',
        ),
    ]
