# Generated by Django 4.2.11 on 2025-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_saveditem_unique_user_relation_entity_related_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the profile.', verbose_name='Last update'),
        ),
    ]
