# Generated by Django 4.2.11 on 2025-05-15 14:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField()),
                ('description', models.TextField()),
                ('logic', models.JSONField(blank=True, help_text='Logic fields for badge criteria.', null=True)),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='ID from external badge provider, if applicable.', max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.ActiveUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_displayed', models.BooleanField(default=True)),
                ('progress', models.IntegerField(blank=True, help_text='Current progress towards earning this badge.', null=True)),
                ('target', models.IntegerField(blank=True, help_text='Target value to earn this badge.', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(through='users.UserBadge', to='users.profile'),
        ),
    ]
