# Generated by Django 4.2.11 on 2025-05-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_customuser_managers_letsconnectlog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField()),
                ('description', models.TextField()),
                ('logic', models.JSONField(blank=True, help_text='Logic fields for badge criteria.', null=True)),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='ID from external badge provider, if applicable.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Progress towards the badge.')),
                ('is_displayed', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(through='users.UserBadge', to='users.profile'),
        ),
    ]
