# Generated by Django 4.2.11 on 2025-05-16 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_badge_userbadge_badge_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='profile',
        ),
    ]
