# Generated by Django 4.2.11 on 2025-05-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_badge_userbadge_badge_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
    ]
