# Generated by Django 5.1.11 on 2025-07-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_userbadge_unique_together_remove_badge_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automated_lets_connect',
            field=models.BooleanField(blank=True, default=None, help_text='Temporary field indicating whether the user has automated lets connect integration.', null=True, verbose_name='Automated lets connect'),
        ),
    ]
