# Generated by Django 5.1 on 2025-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_add_automated_lets_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar_url',
            field=models.URLField(help_text='URL of the avatar', max_length=512, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='picture',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL of the profile image from Commons.', max_length=512, null=True, verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='wikimediaproject',
            name='wikimedia_project_picture',
            field=models.URLField(blank=True, help_text='Picture of the Wikimedia project', max_length=512, verbose_name='Wikimedia project picture'),
        ),
    ]
