# Generated by Django 5.1 on 2025-09-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_avatar_avatar_url_alter_badge_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='external_id',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='external_assertion_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='external_issued_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
