# Generated by Django 5.1.9 on 2025-10-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_badge_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('partner', 'Partner')], default='internal', max_length=10),
        ),
    ]
