# Generated by Django 5.1.9 on 2025-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_skill_type_skill_skill_type'),
        ('users', '0030_alter_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills_known',
            field=models.ManyToManyField(blank=True, help_text='List of IDs of skills that the user knows.', related_name='user_known_skills', to='skills.skill', verbose_name='Known capacity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, help_text='List of IDs of skills that the user wants to learn.', related_name='user_desired_skills', to='skills.skill', verbose_name='Wanted capacity'),
        ),
    ]
