# Generated by Django 5.1.9 on 2025-11-20 15:29

import users.models.profile
from django.db import migrations, models


def validate_existing_wiki_alt(apps, schema_editor):
    """Data migration: validate existing wiki_alt values.

    For each Profile:
    - Blank wiki_alt if it does not exist on Wikimedia (Meta-Wiki API) OR
      if it duplicates a primary CustomUser.username.
    - On API errors/timeouts, leave value unchanged to avoid blocking migration.
    """
    profile_model = apps.get_model('users', 'Profile')
    user_model = apps.get_model('users', 'CustomUser')

    try:
        import requests
    except Exception:
        # If requests somehow unavailable, abort gracefully.
        return

    # Preload set of primary usernames for quick membership tests
    primary_usernames = set(user_model.objects.values_list('username', flat=True))

    profiles = profile_model.objects.exclude(wiki_alt="").only('id', 'wiki_alt')
    for p in profiles:
        original = p.wiki_alt
        blank = False
        # Duplicate of primary username?
        if original in primary_usernames:
            blank = True
        else:
            # Validate existence on Wikimedia
            try:
                resp = requests.get(
                    "https://meta.wikimedia.org/w/api.php",
                    params={
                        "action": "query",
                        "format": "json",
                        "list": "users",
                        "ususers": original,
                    },
                    timeout=5,
                    headers={"User-Agent": "CapX/1.0 data-migration"},
                )
                resp.raise_for_status()
                data = resp.json()
                users = data.get("query", {}).get("users", [])
                if not users or users[0].get("missing") is not None:
                    blank = True
            except Exception:
                # Network/API issue: keep value; do not blank
                pass
        if blank:
            profile_model.objects.filter(id=p.id).update(wiki_alt="")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_profile_skills_known_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wiki_alt',
            field=models.CharField(blank=True, help_text='Wikimedia alternative account of the user.', max_length=128, validators=[users.models.profile.validate_wiki_alt], verbose_name='Wikimedia alternative account'),
        ),
        migrations.RunPython(validate_existing_wiki_alt, migrations.RunPython.noop),
    ]
