# Generated by Django 5.1.9 on 2025-12-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_wiki_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
