# Generated by Django 5.1.9 on 2026-01-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_language',
            field=models.ForeignKey(default=None, help_text="Language of the user's bio.", null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.language', verbose_name='Bio language'),
        ),
    ]
