# Generated by Django 4.2.11 on 2024-10-24 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_alter_organization_territory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_alter_skill_skill_type_and_more'),
        ('events', '0003_alter_eventorganizations_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizations',
            name='confirmed_organization',
            field=models.BooleanField(default=False, help_text='Is the participation confirmed by the organization?'),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='confirmed_organizer',
            field=models.BooleanField(default=False, help_text='Is the participation confirmed by the organizer?'),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the participation was created.'),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='event',
            field=models.ForeignKey(help_text='Event where the organization is part of.', on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='organization',
            field=models.ForeignKey(help_text='Organization which is part of the event.', on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('sponsor', 'Sponsor'), ('supporter', 'Supporter')], help_text='Role of the organization.', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventorganizations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when the participation was last updated.'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='confirmed_organizer',
            field=models.BooleanField(default=False, help_text='Is the participation confirmed by the organizer?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='confirmed_participant',
            field=models.BooleanField(default=False, help_text='Is the participation confirmed by the participant?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the participation was created.'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(help_text='Event of the participant.', on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(help_text='Account of the participant.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('committee', 'Committee'), ('volunteer', 'Volunteer')], help_text='Role of the participant.', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when the participation was last updated.'),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the event was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(help_text='Creator of the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Event Creator'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(help_text='Name of the event.', max_length=128, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='openstreetmap_id',
            field=models.URLField(blank=True, help_text='OpenStreetMap ID of the event location.', validators=[django.core.validators.RegexValidator(message='Invalid OpenStreetMap ID format. The format should be https://www.openstreetmap.org/(way|node|relation)/12345', regex='^https://www\\.openstreetmap\\.org/(node|way|relation)/\\d+$')], verbose_name='OpenStreetMap ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizations',
            field=models.ManyToManyField(help_text='Organizations of the event.', through='events.EventOrganizations', to='orgs.organization', verbose_name='Event Organizations'),
        ),
        migrations.AlterField(
            model_name='events',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills related to the event.', to='skills.skill', verbose_name='Related Skills'),
        ),
        migrations.AlterField(
            model_name='events',
            name='team',
            field=models.ManyToManyField(help_text='Team members of the event.', related_name='team_members', through='events.EventParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Event Team'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_begin',
            field=models.DateTimeField(help_text='Start time of the event.', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(help_text='End time of the event.', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type_of_location',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], help_text='Type of location of the event.', max_length=20, verbose_name='Type of Location'),
        ),
        migrations.AlterField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when the event was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the event.', verbose_name='Event URL'),
        ),
        migrations.AlterField(
            model_name='events',
            name='wikidata_qid',
            field=models.CharField(blank=True, help_text='Wikidata Qid of the event.', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Wikidata Qid format. The format should be Q12345', regex='^Q[1-9]\\d*$')], verbose_name='Wikidata Qid'),
        ),
    ]
