# Generated by Django 4.2.11 on 2024-11-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventorganizations_confirmed_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='wikilearn_id',
            field=models.CharField(blank=True, help_text='Wikilearn ID of the event.', max_length=100, verbose_name='Wikilearn ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(blank=True, help_text='End time of the event.', verbose_name='End Time'),
        ),
    ]
