# Generated by Django 4.2.11 on 2025-01-18 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventorganizations_confirmed_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the event image on Wikimedia Commons.', validators=[django.core.validators.RegexValidator(message='Invalid Wikimedia Commons URL format. The format should be https://commons.wikimedia.org/wiki/File:Example.jpg', regex='^https://commons\\.wikimedia\\.org/wiki/File:.+$')], verbose_name='Image URL'),
        ),
    ]
