# Generated by Django 4.2.11 on 2025-03-13 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the event image on Wikimedia Commons or Learn Wiki.', validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:Example.jpg or https://learn.wiki/asset...', regex='^(https://commons\\.wikimedia\\.org/wiki/File:.+|https://learn\\.wiki/asset.+)$')], verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(blank=True, help_text='End time of the event.', verbose_name='End Time'),
        ),
    ]
