# Generated by Django 4.2.11 on 2025-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_image_url_alter_events_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the event.', verbose_name='Event Description'),
        ),
    ]
