# Generated by Django 4.2.11 on 2025-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_organization_report'),
        ('events', '0007_events_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='events',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='events',
            name='team',
        ),
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orgs.organization', verbose_name='Event Organization'),
        ),
        migrations.DeleteModel(
            name='EventOrganizations',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
