# Generated by Django 4.2.11 on 2025-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion
from django.core.exceptions import ValidationError

def remove_creator_field(apps, schema_editor): # pragma: no cover
    event_model = apps.get_model('events', 'Events')
    for event in event_model.objects.all():
        if event.organizations.exists():
            event.organization = event.organizations.first()
        else:
            org_model = apps.get_model('orgs', 'Organization')
            organization = org_model.objects.filter(managers__id=event.creator.id).first()
            if organization:
                event.organization = organization
            else:
                raise ValidationError("No organization found for event with creator ID: {}".format(event.creator.id))
        event.save()

def add_creator_field(apps, schema_editor): # pragma: no cover
    event_model = apps.get_model('events', 'Events')
    for event in event_model.objects.all():
        if event.organization:
            event.creator = event.organization.managers.first()
            event.save()
        else:
            raise ValidationError("No creator found for event with ID: {}".format(event.id))


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_organization_report'),
        ('events', '0007_events_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='events',
            name='team',
        ),
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orgs.organization', verbose_name='Event Organization'),
        ),
        migrations.RunPython(
            remove_creator_field,
            add_creator_field,
        ),
        migrations.AlterField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with the event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.organization', verbose_name='Event Organization'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='organizations',
        ),
        migrations.DeleteModel(
            name='EventOrganizations',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
