# Generated by Django 5.1 on 2025-07-18 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventparticipant_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the event image on Wikimedia Commons or Learn Wiki.', max_length=512, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:Example.jpg or https://learn.wiki/asset...', regex='^(https://commons\\.wikimedia\\.org/wiki/File:.+|https://learn\\.wiki/asset.+)$')], verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='events',
            name='openstreetmap_id',
            field=models.URLField(blank=True, help_text='OpenStreetMap ID of the event location.', max_length=512, validators=[django.core.validators.RegexValidator(message='Invalid OpenStreetMap ID format. The format should be https://www.openstreetmap.org/(way|node|relation)/12345', regex='^https://www\\.openstreetmap\\.org/(node|way|relation)/\\d+$')], verbose_name='OpenStreetMap ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the event.', max_length=512, verbose_name='Event URL'),
        ),
    ]
