# Generated by Django 5.1.9 on 2025-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_events_image_url_alter_events_openstreetmap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time_end',
            field=models.DateTimeField(blank=True, help_text='End time of the event.', null=True, verbose_name='End Time'),
        ),
    ]
