# Generated by Django 4.2.11 on 2025-01-07 23:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0006_alter_organization_acronym_and_more'),
        ('skills', '0004_alter_skill_skill_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The full name of the project.', max_length=255)),
                ('profile_image', models.URLField(blank=True, help_text='The URL of the project profile image on Wikimedia Commons.', null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')])),
                ('description', models.TextField(blank=True, help_text='The description of the project.', null=True)),
                ('url', models.URLField(blank=True, help_text='The URL of the project.', null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the project was added on the platform.')),
                ('creator', models.ForeignKey(help_text='The ID of the user who added the project on the platform.', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('related_skills', models.ManyToManyField(blank=True, help_text='The skills related to the project.', related_name='related_skills', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(help_text='The ID of the organization.', on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('project', models.ForeignKey(help_text='The ID of the project.', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemberAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, help_text='The status of the project member.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the project member was accepted.')),
                ('project_member', models.ForeignKey(help_text='The ID of the project member.', on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember')),
            ],
        ),
    ]
