# Generated by Django 4.2.11 on 2025-01-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(help_text='The ID of the project.', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='projects.project'),
        ),
    ]
