# Generated by Django 5.1 on 2025-07-18 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmember_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile_image',
            field=models.URLField(blank=True, help_text='The URL of the project profile image on Wikimedia Commons.', max_length=512, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='The URL of the project.', max_length=512, null=True),
        ),
    ]
