"""
Management command to seed the database with the full list of languages
used in Wikimedia projects.

Usage:
    python3 manage.py seed_languages
"""

from django.core.management.base import BaseCommand
from django.db import transaction
from users.models import Language

# Full language list: (language_name, language_code, language_autonym)
# Derived from the Wikimedia MediaWiki language registry and production data.
LANGUAGES = [
    ("Brazilian Portuguese", "pt-br", "português do Brasil"),
    ("Portuguese", "pt", "português"),
    ("English", "en", "English"),
    ("Spanish", "es", "español"),
    ("French", "fr", "français"),
    ("German", "de", "Deutsch"),
    ("Japanese", "ja", "日本語"),
    ("Abkhazian", "ab", "аԥсшәа"),
    ("Abron", "abr", "Abron"),
    ("Kwéyòl Sent Lisi", "acf", "Kwéyòl Sent Lisi"),
    ("Iraqi Arabic", "acm", "عراقي"),
    ("Afrikaans", "af", "Afrikaans"),
    ("Assyrian Neo-Aramaic", "aii", ""),
    ("Gheg Albanian", "aln", "Gegë"),
    ("Southern Altai", "alt", "алтай тил"),
    ("Aragonese", "an", "aragonés"),
    ("Old English", "ang", "Ænglisc"),
    ("Angika", "anp", "अंगिका"),
    ("Levantine Arabic", "apc", "شامي"),
    ("Arabic", "ar", "العربية"),
    ("Mapuche", "arn", "mapudungun"),
    ("Moroccan Arabic", "ary", "الدارجة"),
    ("Egyptian Arabic", "arz", "مصرى"),
    ("Assamese", "as", "অসমীয়া"),
    ("American Sign Language", "ase", "American sign language"),
    ("Asturian", "ast", "asturianu"),
    ("Avaric", "av", "авар"),
    ("Aymara", "ay", "Aymar aru"),
    ("Azerbaijani", "az", "azərbaycanca"),
    ("South Azerbaijani", "azb", "تۆرکجه"),
    ("Bashkir", "ba", "башҡортса"),
    ("Balinese", "ban", "ᬩᬲᬩᬮᬶ"),
    ("Southern Balochi", "bcc", "بلوچی مکرانی"),
    ("Central Bikol", "bcl", "Bikol Central"),
    ("West Coast Bajau", "bdr", ""),
    ("Belarusian", "be", "беларуская"),
    ("Belarusian (Taraškievica orthography)", "be-tarask", "беларуская (тарашкевіца)"),
    ("Betawi", "bew", "Betawi"),
    ("Bulgarian", "bg", "български"),
    ("Haryanvi", "bgc", "हरियाणवी"),
    ("Bini", "bin", "Edo"),
    ("Banjar", "bjn", "Bahasa Banjar"),
    ("Pa'O", "blk", "ပအိုဝ်ႏဘာႏသာႏ"),
    ("Bangla", "bn", "বাংলা"),
    ("Bishnupriya", "bpy", "ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী"),
    ("Breton", "br", "brezhoneg"),
    ("Bosnian", "bs", "bosanski"),
    ("Batak Mandailing", "btm", "Batak Mandailing"),
    ("Russia Buriat", "bxr", "буряад"),
    ("Catalan", "ca", "català"),
    ("Kaqchikel", "cak", "Kaqchikel"),
    ("Chakma", "ccp", "𑄌𑄋𑄴𑄟𑄳𑄦"),
    ("Chechen", "ce", "нохчийн"),
    ("Cebuano", "ceb", "Cebuano"),
    ("Chinook Jargon", "chn", "Chinook Wawa"),
    ("Central Kurdish", "ckb", "کوردیی ناوەندی"),
    ("Corsican", "co", "corsu"),
    ("Crimean Tatar (Cyrillic script)", "crh-cyrl", "Qırımtatarca"),
    ("Crimean Tatar (Latin script)", "crh-latn", "qırımtatarca"),
    ("Dobrujan Tatar", "crh", "qırımtatarca"),
    ("Czech", "cs", "čeština"),
    ("Church Slavic", "cu", "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ"),
    ("Chuvash", "cv", "чӑвашла"),
    ("Welsh", "cy", "Cymraeg"),
    ("Danish", "da", "dansk"),
    ("Dagbani", "dag", "Dagbanli"),
    ("Dargwa", "dar", "дарган"),
    ("German (formal address)", "de-formal", "Deutsch (Sie-Form)"),
    ("Dagaare", "dga", ""),
    ("Zazaki", "diq", "Zazaki"),
    ("Lower Sorbian", "dsb", "dolnoserbski"),
    ("Central Dusun", "dtp", "Kadazandusun"),
    ("ẹkpeye", "efi", ""),
    ("Greek", "el", "Ελληνικά"),
    ("Canadian English", "en-ca", "Canadian English"),
    ("British English", "en-gb", "British English"),
    ("Esperanto", "eo", "Esperanto"),
    ("Estonian", "et", "eesti"),
    ("Basque", "eu", "euskara"),
    ("Extremaduran", "ext", "estremeñu"),
    ("Persian", "fa", "فارسی"),
    ("Fanti", "fat", ""),
    ("Finnish", "fi", "suomi"),
    ("Tornedalen Finnish", "fit", "meänkieli"),
    ("Faroese", "fo", "føroyskt"),
    ("Cajun French", "frc", "français cadien"),
    ("Arpitan", "frp", "arpetan"),
    ("Northern Frisian", "frr", "Nordfriisk"),
    ("Friulian", "fur", "furlan"),
    ("Western Frisian", "fy", "Frysk"),
    ("Irish", "ga", "Gaeilge"),
    ("Gagauz", "gag", "Gagauz"),
    ("Guadeloupean Creole", "gcf", ""),
    ("Scottish Gaelic", "gd", "Gàidhlig"),
    ("Galician", "gl", "galego"),
    ("Goan Konkani (Latin script)", "gom-latn", "Gõychi Konknni"),
    ("Gorontalo", "gor", "Bahasa Hulontalo"),
    ("Ghanaian Pidgin", "gpe", ""),
    ("Alemannic", "als", "Alemannisch"),
    ("Gujarati", "gu", "ગુજરાતી"),
    ("Frafra", "gur", ""),
    ("Hausa", "ha", "Hausa"),
    ("Hebrew", "he", "עברית"),
    ("Hindi", "hi", "हिन्दी"),
    ("Fiji Hindi (Latin script)", "hif-latn", "Fiji Hindi"),
    ("Hiligaynon", "hil", "Ilonggo"),
    ("Croatian", "hr", "hrvatski"),
    ("Upper Sorbian", "hsb", "hornjoserbsce"),
    ("Xiang", "hsn", ""),
    ("Haitian Creole", "ht", "Kreyòl ayisyen"),
    ("Hungarian", "hu", "magyar"),
    ("Armenian", "hy", "հայերեն"),
    ("Western Armenian", "hyw", "Արեւմտահայերէն"),
    ("Interlingua", "ia", "interlingua"),
    ("Iban", "iba", "Jaku Iban"),
    ("Ibibio", "ibb", ""),
    ("Indonesian", "id", "Bahasa Indonesia"),
    ("Igbo", "ig", "Igbo"),
    ("Igala", "igl", ""),
    ("Sichuan Yi", "ii", "ꆇꉙ"),
    ("Iloko", "ilo", "Ilokano"),
    ("Ingush", "inh", "ГӀалгӀай"),
    ("Ido", "io", "Ido"),
    ("Icelandic", "is", "íslenska"),
    ("awain", "awa", "अवधी"),
    ("меджусловјанскы", "isv", "меджусловјанскы"),
    ("medžuslovjansky", "isv-latn", "medžuslovjansky"),
    ("Italian", "it", "italiano"),
    ("Ingrian", "izh", ""),
    ("Javanese", "jv", "Jawa"),
    ("Georgian", "ka", "ქართული"),
    ("Kara-Kalpak", "kaa", "Qaraqalpaqsha"),
    ("Kabyle", "kab", "Taqbaylit"),
    ("Tyap", "kcg", ""),
    ("tjikalanga", "kck", ""),
    ("Kongo", "kg", "Kongo"),
    ("Khakas", "kjh", "хакас"),
    ("Eastern Pwo", "kjp", "ဖၠုံလိက်"),
    ("Kazakh (Cyrillic script)", "kk-cyrl", "қазақша"),
    ("Khmer", "km", "ខ្មែរ"),
    ("Kannada", "kn", "ಕನ್ನಡ"),
    ("Korean", "ko", "한국어"),
    ("Korean (North Korea)", "ko-kp", "한국어 (조선)"),
    ("Komi-Permyak", "koi", "Перем Коми"),
    ("Karachay-Balkar", "krc", "Къарачай-Малкъар"),
    ("Krio", "kri", ""),
    ("Kashmiri (Arabic script)", "ks-arab", "کٲشُر"),
    ("Colognian", "ksh", "Ripoarisch"),
    ("Kurdish (Latin script)", "ku", "kurdî"),
    ("Kumyk", "kum", "Къумукъ"),
    ("Komi", "kv", "коми"),
    ("Kyrgyz", "ky", "Кыргызча"),
    ("Luxembourgish", "lb", "Lëtzebuergesch"),
    ("Ganda", "lg", "Luganda"),
    ("Limburgish", "li", "Limburgs"),
    ("Ligurian", "lij", "Ligure"),
    ("Laki", "lki", ""),
    ("Lombard", "lmo", "lombard"),
    ("Lingala", "ln", "lingála"),
    ("Northern Luri", "lrc", "لۊری شومالی"),
    ("Lithuanian", "lt", "lietuvių"),
    ("Luba-Lulua", "lua", "Tshiluba"),
    ("Mizo", "lus", "Mizo ṭawng"),
    ("Latvian", "lv", "latviešu"),
    ("Literary Chinese", "lzh", "文言"),
    ("Magahi", "mag", ""),
    ("Moksha", "mdf", "мокшень"),
    ("Hassaniya Arabic", "mey", ""),
    ("Malagasy", "mg", "Malagasy"),
    ("Eastern Mari", "mhr", "олык марий"),
    ("Minangkabau", "min", "Minangkabau"),
    ("Macedonian", "mk", "македонски"),
    ("Malayalam", "ml", "മലയാളം"),
    ("Manchu", "mnc", "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ"),
    ("Manchu (Latin script)", "mnc-latn", "Manju gisun"),
    ("Manchu (Mongolian script)", "mnc-mong", ""),
    ("Manipuri", "mni", "ꯃꯤꯇꯩ ꯂꯣꯟ"),
    ("Mon", "mnw", "ဘာသာ မန်"),
    ("Moldovan", "mo", ""),
    ("Mossi", "mos", "Moore"),
    ("Marathi", "mr", "मराठी"),
    ("Mara", "mrh", ""),
    ("Western Mari", "mrj", "кырык мары"),
    ("Malay", "ms", "Bahasa Melayu"),
    ("Malay (Jawi script)", "ms-arab", "بهاس ملايو"),
    ("Bahasa Sabah", "ms-sab", ""),
    ("Maltese", "mt", "Malti"),
    ("Musi", "mui", ""),
    ("Burmese", "my", "မြန်မာဘာသာ"),
    ("Erzya", "myv", "эрзянь"),
    ("Mazanderani", "mzn", "مازِرونی"),
    ("Nāhuatl", "nah", "Nāhuatl"),
    ("Minnan", "nan", "Bân-lâm-gú"),
    ("闽南语（简化汉字）", "nan-hans", ""),
    ("Minnan (Traditional Han script)", "nan-hant", ""),
    ("Neapolitan", "nap", "Napulitano"),
    ("Norwegian Bokmål", "nb", "norsk bokmål"),
    ("Low German", "nds", "Plattdüütsch"),
    ("Nepali", "ne", "नेपाली"),
    ("Dutch", "nl", "Nederlands"),
    ("Norwegian Nynorsk", "nn", "norsk nynorsk"),
    ("Norwegian", "no", "norsk"),
    ("Northern Thai", "nod", "ᨣᩤᩴᨾᩮᩬᩥᨦ"),
    ("N'Ko", "nqo", "ߒߞߏ"),
    ("Nupe", "nup", ""),
    ("Nyoro", "nyn", "runyankore"),
    ("Nzima", "nzi", ""),
    ("Occitan", "oc", "occitan"),
    ("Northwestern Ojibwa", "ojb", ""),
    ("Livvi-Karelian", "olo", "Livvi"),
    ("Odia", "or", "ଓଡ଼ିଆ"),
    ("Punjabi", "pa", "ਪੰਜਾਬੀ"),
    ("Nigerian Pidgin", "pcm", "Naijá"),
    ("Petjoh", "pey", ""),
    ("Polish", "pl", "polski"),
    ("Piedmontese", "pms", "Piemontèis"),
    ("Western Punjabi", "pnb", "پنجابی"),
    ("Pashto", "ps", "پښتو"),
    ("Quechua", "qu", "Runa Simi"),
    ("Riffian", "rif", "Tarifit"),
    ("Romansh", "rm", "rumantsch"),
    ("Romanian", "ro", "română"),
    ("Tarantino", "roa-tara", "tarandíne"),
    ("Pannonian Rusyn", "rue", "русиньскый"),
    ("Russian", "ru", "русский"),
    ("Rusyn", "ruq", ""),
    ("Aromanian", "rup", "armãneashti"),
    ("Rutul", "rut", ""),
    ("Kinyarwanda", "rw", "Ikinyarwanda"),
    ("Yakut", "sah", "саха тыла"),
    ("Santali", "sat", "ᱥᱟᱱᱛᱟᱲᱤ"),
    ("Sardinian", "sc", "sardu"),
    ("Sicilian", "scn", "sicilianu"),
    ("Scots", "sco", "Scots"),
    ("Sindhi", "sd", "سنڌي"),
    ("Southern Kurdish", "sdh", "کوردی خوارگ"),
    ("Northern Sami", "se", "davvisámegiella"),
    ("Sango", "sg", "Sängö"),
    ("Serbo-Croatian", "sh", "srpskohrvatski / српскохрватски"),
    ("Serbo-Croatian (Cyrillic script)", "sh-cyrl", "српскохрватски"),
    ("Serbo-Croatian (Latin script)", "sh-latn", "srpskohrvatski"),
    ("Shan", "shn", "ၽႃႇသႃႇတႆး "),
    ("Sinhala", "si", "සිංහල"),
    ("Kildin Sami", "sjd", ""),
    ("Pite Sami", "sje", ""),
    ("Slovak", "sk", "slovenčina"),
    ("Saraiki (Arabic script)", "skr-arab", "سرائیکی"),
    ("Slovenian", "sl", "slovenščina"),
    ("Inari Sami", "smn", "anarâškielâ"),
    ("Skolt Sami", "sms", "sääʹmǩiõll"),
    ("Shona", "sn", "chiShona"),
    ("Albanian", "sq", "shqip"),
    ("Serbian (Cyrillic script)", "sr", "српски"),
    ("Serbian (Latin script)", "sr-el", "srpski (latinica)"),
    ("Southern Sotho", "st", "Sesotho"),
    ("Saterland Frisian", "stq", "Seeltersk"),
    ("Siberian Tatar", "sty", ""),
    ("Sundanese", "su", "Sunda"),
    ("Swedish", "sv", "svenska"),
    ("Swahili", "sw", "Kiswahili"),
    ("Sylheti", "syl", "ꠍꠤꠟꠐꠤ"),
    ("Sakizaya", "szy", "Sakizaya"),
    ("Tamil", "ta", "தமிழ்"),
    ("Tulu", "tcy", "ತುಳು"),
    ("Tai Nuea", "tdd", ""),
    ("Telugu", "te", "తెలుగు"),
    ("Tajik (Cyrillic script)", "tg", "тоҷикӣ"),
    ("Tajik (Latin script)", "tg-latn", "tojikī"),
    ("Thai", "th", "ไทย"),
    ("Bifzivsar", "tif", ""),
    ("Turkmen", "tk", "Türkmençe"),
    ("Tagalog", "tl", "Tagalog"),
    ("Talysh", "tly", "tolışi"),
    ("Tswana", "tn", "Setswana"),
    ("Toki Pona", "tok", "toki pona"),
    ("Turkish", "tr", "Türkçe"),
    ("Tatar (Cyrillic script)", "tt", "татарча/tatarça"),
    ("Tooro", "ttj", "Rutooro"),
    ("Twi", "tw", "Twi"),
    ("Udmurt", "udm", "удмурт"),
    ("Uyghur (Arabic script)", "ug-arab", "ئۇيغۇرچە"),
    ("Ukrainian", "uk", "українська"),
    ("Urdu", "ur", "اردو"),
    ("Uzbek", "uz", "oʻzbekcha/ўзбекча"),
    ("Venetian", "vec", "vèneto"),
    ("Veps", "vep", "vepsän kel'"),
    ("Vietnamese", "vi", "Tiếng Việt"),
    ("Volapük", "vo", "Volapük"),
    ("Votic", "vot", ""),
    ("Wolaytta", "wal", ""),
    ("waale", "wbl", ""),
    ("గోండి", "wdd", ""),
    ("Wu (Traditional Han script)", "wuu", "吴语"),
    ("Kalmyk", "xal", "хальмг"),
    ("Mingrelian", "xmf", "მარგალური"),
    ("Yiddish", "yi", "ייִדיש"),
    ("Yoruba", "yo", "Yorùbá"),
    ("Nheengatu", "yrl", ""),
    ("Cantonese (Traditional Han script)", "yue", "粵語"),
    ("Standard Moroccan Tamazight", "zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ"),
    ("Chinese", "zh", "中文"),
    ("Simplified Chinese", "zh-hans", "中文（简体）"),
    ("Traditional Chinese", "zh-hant", "中文（繁體）"),
    ("Chinese (Hong Kong)", "zh-hk", "中文（香港）"),
    ("Zulu", "zu", "isiZulu"),
]


class Command(BaseCommand):
    help = "Seed the database with the full Wikimedia language list (304 unique languages)"

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        with transaction.atomic():
            for language_name, language_code, language_autonym in LANGUAGES:
                _, created = Language.objects.update_or_create(
                    language_code=language_code,
                    defaults={
                        "language_name": language_name,
                        "language_autonym": language_autonym,
                    },
                )
                if created:
                    created_count += 1
                else:
                    updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Done. Created: {created_count}, Updated: {updated_count}, "
            f"Total in DB: {Language.objects.count()}"
        ))
