# Generated by Django 5.1.12 on 2025-11-24 17:13

import django.db.models.deletion
import translate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabaseOAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=translate.models.generate_state, max_length=64, unique=True)),
                ('request_token', models.CharField(max_length=255, unique=True)),
                ('request_secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metabase_oauth_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
