# Generated by Django 4.2.11 on 2024-10-24 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_language_language_autonym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0005_alter_organization_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(help_text='The acronym of the organization (if any).', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='display_name',
            field=models.CharField(help_text='The full name of the organization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='home_project',
            field=models.URLField(blank=True, help_text='The URL of the home project of the organization on Wikimedia (e.g. https://xx.wikimedia.org/).', null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://xx.wikimedia.org/', regex='^https:\\/\\/[\\w-]+\\.wikimedia\\.org\\/$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='ID of users who are managers of the organization on the platform.', related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='meta_page',
            field=models.URLField(blank=True, help_text='The URL of the organization page on Meta-Wiki.', null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://meta.wikimedia.org/wiki/PageName', regex='^https:\\/\\/meta\\.wikimedia\\.org\\/wiki\\/.*?$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_image',
            field=models.URLField(blank=True, help_text='The URL of the organization profile image on Wikimedia Commons.', null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='territory',
            field=models.ManyToManyField(blank=True, help_text='The territories where the organization is active.', related_name='territory', to='users.territory'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(help_text='The type of the organization as defined in the OrganizationType model.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='orgs.organizationtype'),
        ),
    ]
