# Generated by Django 4.2.11 on 2025-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_organization_acronym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mastodon',
            field=models.URLField(blank=True, help_text='The URL of the organization Mastodon account.', null=True),
        ),
    ]
