# Generated by Django 4.2.11 on 2025-01-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_organization_mastodon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tag_diff',
            field=models.CharField(blank=True, default='', help_text='The tag used by the organization on Diff posts (if any).', max_length=255),
        ),
    ]
