# Generated by Django 4.2.11 on 2025-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_skill_type_and_more'),
        ('orgs', '0008_organization_tag_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_capacities',
            field=models.ManyToManyField(blank=True, help_text='The available capacities of the organization.', related_name='available_capacities', to='skills.skill', verbose_name='Available capacities'),
        ),
        migrations.AddField(
            model_name='organization',
            name='known_capacities',
            field=models.ManyToManyField(blank=True, help_text='The known capacities of the organization.', related_name='known_capacities', to='skills.skill', verbose_name='Known capacities'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wanted_capacities',
            field=models.ManyToManyField(blank=True, help_text='The wanted capacities of the organization.', related_name='wanted_capacities', to='skills.skill', verbose_name='Wanted capacities'),
        ),
    ]
