# Generated by Django 4.2.11 on 2025-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_tag_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the organization.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='The URL of the organization website.', null=True),
        ),
    ]
