# Generated by Django 4.2.11 on 2025-01-17 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organization_available_capacities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the organization.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='The URL of the organization website.', null=True),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tag_diff',
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_diff',
            field=models.ManyToManyField(blank=True, help_text='The tag used by the organization on Diff posts (if any).', related_name='tag_diff', to='orgs.tagdiff'),
        ),
    ]
