# Generated by Django 4.2.11 on 2025-01-11 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organization_email_organization_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tag_diff',
        ),
        migrations.AddField(
            model_name='organization',
            name='tag_diff',
            field=models.ManyToManyField(blank=True, help_text='The tag used by the organization on Diff posts (if any).', related_name='tag_diff', to='orgs.tagdiff'),
        ),
    ]
