# Generated by Django 4.2.11 on 2025-01-18 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_tagdiff_organization_email_organization_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the document on Wikimedia Commons.', validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='The documents related to the organization.', related_name='documents', to='orgs.document'),
        ),
    ]
