# Generated by Django 4.2.11 on 2025-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_document_organization_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report',
            field=models.URLField(blank=True, help_text='The URL of the organization report.', null=True),
        ),
    ]
