# Generated by Django 5.1.1 on 2025-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_image_url_alter_events_time_end'),
        ('orgs', '0012_organization_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='choose_events',
            field=models.ManyToManyField(blank=True, help_text='Highlighted events chosen by the organization.', related_name='highlighted_by_organizations', to='events.events'),
        ),
    ]
