# Generated by Django 4.2.11 on 2025-05-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def move_managers_to_management(apps, schema_editor): # pragma: no cover
    organization = apps.get_model('orgs', 'Organization')
    management = apps.get_model('orgs', 'Management')

    for org in organization.objects.all():
        for user in org.managers.all():
            management.objects.create(
                organization=org,
                user=user,
                joined_at=org.update_date,
            )

def move_managers_to_management_reverse(apps, schema_editor): # pragma: no cover
    management = apps.get_model('orgs', 'Management')

    for mgmt in management.objects.all():
        org = mgmt.organization
        user = mgmt.user
        org.managers.add(user)
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0013_organization_choose_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(help_text='The organization managed by the user.', on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('user', models.ForeignKey(help_text='The user who manages the organization.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            move_managers_to_management,
            move_managers_to_management_reverse,
        ),
        migrations.RemoveField(
            model_name='organization',
            name='managers',
        ),
        migrations.AddField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='ID of users who are managers of the organization on the platform.', related_name='managers', through='orgs.Management', to=settings.AUTH_USER_MODEL),
        ),
    ]
