# Generated by Django 5.1 on 2025-07-18 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_management_alter_organization_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(help_text='The URL of the document on Wikimedia Commons.', max_length=512, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='home_project',
            field=models.URLField(blank=True, help_text='The URL of the home project of the organization on Wikimedia (e.g. https://xx.wikimedia.org/).', max_length=512, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://xx.wikimedia.org/', regex='^https:\\/\\/[\\w-]+\\.wikimedia\\.org\\/$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mastodon',
            field=models.URLField(blank=True, help_text='The URL of the organization Mastodon account.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='meta_page',
            field=models.URLField(blank=True, help_text='The URL of the organization page on Meta-Wiki.', max_length=512, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://meta.wikimedia.org/wiki/PageName', regex='^https:\\/\\/meta\\.wikimedia\\.org\\/wiki\\/.*?$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_image',
            field=models.URLField(blank=True, help_text='The URL of the organization profile image on Wikimedia Commons.', max_length=512, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report',
            field=models.URLField(blank=True, help_text='The URL of the organization report.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='The URL of the organization website.', max_length=512, null=True),
        ),
    ]
