# Generated by Django 5.1.9 on 2025-11-14 13:15

import django.db.models.deletion
from django.db import migrations, models

def migrate_display_names(apps, schema_editor): # pragma: no cover
    organization = apps.get_model('orgs', 'Organization')
    organization_name = apps.get_model('orgs', 'OrganizationName')

    for org in organization.objects.all():
        display_name = org.display_name
        if display_name and display_name.strip() != "":
            organization_name.objects.create(
                organization=org,
                language_code='en',
                name=display_name.strip()
            )

def migrate_display_names_reverse(apps, schema_editor): # pragma: no cover
    organization_name = apps.get_model('orgs', 'OrganizationName')

    for org_name in organization_name.objects.filter(language_code='en'):
        org = org_name.organization
        if org_name.name and org_name.name.strip() != "":
            org.display_name = org_name.name.strip()
            org.save(update_fields=['display_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_alter_document_url_alter_organization_home_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='BCP 47 / ISO language code (e.g. en, pt-BR).', max_length=10)),
                ('name', models.CharField(help_text='Localized display name for the organization.', max_length=255)),
                ('organization', models.ForeignKey(help_text='The organization this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='i18n_names', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'language_code'], name='orgs_organi_organiz_5dd639_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'language_code'), name='uniq_org_lang_display_name')],
            },
        ),
        migrations.RunPython(
            code=migrate_display_names,
            reverse_code=migrate_display_names_reverse,
        ),
        migrations.RemoveField(
            model_name='organization',
            name='display_name',
        ),
    ]
