# Generated by Django 4.2.11 on 2024-10-24 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_skill_skill_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.ManyToManyField(blank=True, help_text='ID of the another skill that this skill is a subtype of.', to='skills.skill', verbose_name='Skill type'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_wikidata_item',
            field=models.CharField(default='', help_text='Wikidata item ID of the skill.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated'),
        ),
    ]
