# Generated by Django 5.1.12 on 2026-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_remove_skill_skill_type_skill_skill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='hashtags', to='skills.skill')),
            ],
        ),
    ]
