# Generated by Django 4.2.11 on 2024-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_bug_type_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(blank=True, choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('improvement', 'Improvement'), ('test_case', 'Test Case')], default='error', help_text='Type of the bug.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(help_text='Description of the bug.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('done', 'Done')], default='to_do', help_text='Status of the bug (to be set by the staff).', max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(help_text='Title of the bug.', max_length=200),
        ),
    ]
