# Generated by Django 6.0.3 on 2026-03-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_bug_bug_type_alter_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(blank=True, choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('improvement', 'Improvement'), ('new_capacity', 'New Capacity'), ('test_case', 'Test Case')], default='error', help_text='Type of the bug.', max_length=20),
        ),
    ]
